/* eslint-disable @next/next/no-img-element */
import { Carousel } from "react-bootstrap";
import Head from "next/head";

import EastIcon from "@mui/icons-material/East";
import WestIcon from "@mui/icons-material/West";
import Navbar from "selvatica/components/Navbar/Navbar";

export default function Landing() {
  return (
    <>
      <Head>
        <title>Selvatica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="landing">
        <Navbar />
        <Carousel
          fade
          interval={null}
          indicators={false}
          prevIcon={
            <span className="carousel__button">
              <WestIcon fontSize="inherit" color="inherit" />
            </span>
          }
          nextIcon={
            <span className="carousel__button">
              <EastIcon fontSize="inherit" color="inherit" />
            </span>
          }
        >
          <Carousel.Item>
            <img
              className="d-block"
              src="/images/1-medium.jpg"
              alt="arbicultura image"
            />
          </Carousel.Item>
          <Carousel.Item>
            <img
              className="d-block"
              src="/images/2-medium.jpg"
              alt="arbicultura image"
            />
          </Carousel.Item>
        </Carousel>
      </main>
    </>
  );
}
