import { useEffect, useRef, useState } from "react";
import Head from "next/head";

import BiodiversityLanding from "selvatica/components/Landing/BiodiversityLanding/BiodiversityLanding";
import CarouselLanding from "selvatica/components/Landing/CarouselLanding/CarouselLanding";
import ContactLanding from "selvatica/components/Landing/ContactLanding/ContactLanding";
import ServicesLanding from "selvatica/components/Landing/ServicesLanding/ServicesLanding";
import Navbar from "selvatica/components/shared/Navbar/Navbar";

export default function Landing() {
  const [isMenuOpen, setIsMenuOpen] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Selvatica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`landing`}>
        <Navbar isMenuOpen={isMenuOpen} setIsMenuOpen={setIsMenuOpen} />
        <CarouselLanding isMenuOpen={isMenuOpen} />
        <ServicesLanding />
        <BiodiversityLanding />
        <ContactLanding />
      </main>
    </>
  );
}
